### ISSUE TITLE
question about VDI_PAGE_ZERO

### ISSUE THREAD

**Issue by basinilya** [hakito/SlimVDI#1]
Hi Gerd.
I'm a big fan of snapshots and I hope that someday VirtualBox will be able to combine snapshots and TRIM.

I noticed that you extended the VDI file format and added a new special value VDI_PAGE_ZERO = -2 to the block map. I just wonder, who and when can create differencing VDIs with this value. In this project I only see reading, but not writing VDI_PAGE_ZERO

**Comment by hakito** [comment]
Hi basinilya!

Please keep in mind that this is just a modified version of CloneVDI which didn't have the capability to remove unused blocks in diff images. So please consider asking him directly about this. You can find the CloneVDI discussion here:  https://forums.virtualbox.org/viewtopic.php?t=22422

I'd recommend not to mention SlimVDI.
